### PR TITLE
Upgrade to Prefect 2

### PR DESCRIPTION
**Pull request by BrunoGrandePhD**
On July 27, Prefect [announced](https://www.prefect.io/guide/blog/the-global-coordination-plane) the public release of Prefect 2, which has been in public beta for several months. I opted for Prefect 1 for my original prototype because I wasn't sure of their release timeline for Prefect 2, which they advised against using in production. 

I used the [migration guide](https://docs.prefect.io/migration-guide/) to help identify the bits that needed to be changed. Fortunately, all of the features that I've been using so far are already available in Prefect 2 except for the flow visualization. In fact, I don't know if it's even possible anymore to visualize the flow anymore since they've forgone the DAG concept for a more dynamic approach ([blog post](https://www.prefect.io/guide/blog/workflow-orchestration-without-dags/) for context). Check out this [blog post](https://www.prefect.io/guide/blog/getting-started-prefect-2/) for a more general introduction to Prefect 2.

### CODE REVIEW

**Comment by thomasyu888** [comment]
Looks good so far. What are your thoughts of them forgoing the DAG feature?

**Comment by BrunoGrandePhD** [comment]
My first instinct is that the extra flexibility it affords is worth it. For example, you can now use native Python if-else statements and for-loops instead of the Prefect `case` syntax ([example](https://discourse.prefect.io/t/how-can-i-build-conditional-logic-within-a-flow/61)). That said, it's unclear how much we will benefit from it until I write a Prefect 2 flow from scratch.

**Comment by thomasyu888** [comment]
Very interesting.  One of the benefits I see to this as well is actually the added terminology of a "flow".  I like the fact that flows tie together bioinformatic workflow DAGs.

I'd be curious to see more of how they visualize Flows in the UI.

**Comment by BrunoGrandePhD** [comment]
They visualize them at runtime: https://www.prefect.io/blog/introducing-radar/

**Pull request merged**
